# TrueColorを有効に
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",$TERM:Tc"

set -g default-shell "/home/linuxbrew/.linuxbrew/bin/fish"

setw -g mode-keys vi
set -g mouse on
set -g escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -g focus-events on

# プレフィックスキーをバックスラッシュに
unbind C-b
set -g prefix C-\\

# WayLand (WSL)のクリップボードにコピー
set -g set-clipboard off
set -s copy-command "wl-copy"
# ]キーおよびマウスホイール押しでWayLandのクリップボードからペースト
bind ] run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"
bind -T root MouseDown2Pane run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"

# 新規ウィンドウを開くときに同じディレクトリから始める
bind c new-window -c '#{pane_current_path}'
bind h split-window -c '#{pane_current_path}'
bind v split-window -h -c '#{pane_current_path}'

# ウィンドウの移動のショートカット
# bind -n C-PageUp previous-window
# bind -n C-PageDown next-window
# bind -n C-S-PageUp swap-window -t -1\; select-window -t -1
# bind -n C-S-PageDown swap-window -t +1\; select-window -t +1
bind -n Up previous-window
bind -n Down next-window
bind -n M-Up send Up
bind -n M-Down send Down
bind -T copy-mode-vi Up previous-window
bind -T copy-mode-vi Down next-window
bind -n S-Up swap-window -t -1\; select-window -t -1
bind -n S-Down swap-window -t +1\; select-window -t +1

bind -n C-Up select-pane -U
bind -n C-Down select-pane -D
bind -n C-Left select-pane -L
bind -n C-Right select-pane -R
bind -T copy-mode-vi C-Up select-pane -U
bind -T copy-mode-vi C-Down select-pane -D
bind -T copy-mode-vi C-Left select-pane -L
bind -T copy-mode-vi C-Right select-pane -R

# status line
set -g status-bg "#3c3836"
set -g status-fg "#a89984"
set -g status-justify "centre"
setw -g window-status-separator ""
setw -g window-status-format " #I.#W "
setw -g window-status-current-format "#[bg=#a89984,fg=#282828]#I.#W#[default]"
set -g status-left "#[bg=#b8bb26,fg=#282828] #S#[fg=#b8bb26,bg=#3c3836] "
set -g status-right "#[fg=#504945]#[default,bg=#504945]%m/%d %a #[fg=#b8bb26,bg=#504945]#[bg=#b8bb26,fg=#282828]%H:%M "
